package com.ancraz.mywallet_mult.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val primaryColor = Color(0xFF0DF69D)
val onPrimaryColor = Color(0xFF141416)
val primaryContainerColor = Color(0xFFADF2C6)
val onPrimaryContainerColor = Color(0xFF002111)
val secondaryColor = Color(0xFF242424)
val onSecondaryColor = Color(0xFFFFFFFF)
val secondaryContainer = Color(0xFF9EEFFD)
val onSecondaryContainer = Color(0xFF001F24)
val tertiaryColor = Color(0xFF00ADFA)
val onTertiaryColor = Color(0xFFFFFFFF)
val tertiaryContainer = Color(0xFFCAE6FF)
val onTertiaryContainer = Color(0xFF001E30)
val errorColor = Color(0xFFDF424B)
val onError = Color(0xFFFFFFFF)
val errorContainer = Color(0xFFFFDAD8)
val onErrorContainer = Color(0xFF3B080C)
val backgroundColor = Color(0xFF141416)
val onBackgroundColor = Color(0xFFFFFFFF)
val surfaceColor = Color(0xFF272228)
val onSurfaceColor = Color(0xFFFFFFFF)
val surfaceVariant = Color(0xFFDCE5DC)
val onSurfaceVariantColor = Color(0xFF404942)
val outlineColor = Color(0xFF3e3d43)
val outlineVariant = Color(0xFFC0C9C0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322D)